# Generated by Django 3.2.19 on 2023-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('social_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.ManyToManyField(blank=True, db_table='customer_project', related_name='customers', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
    ]
