# Generated by Django 3.2.19 on 2023-05-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plains', '0004_auto_20230531_0031'),
        ('projects', '0003_auto_20230515_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='plains',
        ),
        migrations.CreateModel(
            name='ProjectPlains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('plain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plains.plain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Plain',
                'verbose_name_plural': 'Project Plains',
                'db_table': 'project_plains',
            },
        ),
    ]
