# Generated by Django 3.2.19 on 2023-05-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20230515_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
    ]
