# Generated by Django 3.2.19 on 2023-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plains', '0002_auto_20230515_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plain',
            name='customer',
        ),
        migrations.AlterField(
            model_name='plain',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plain',
            name='plain_code',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
