# Generated by Django 3.2.19 on 2023-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('plain_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('feeder', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_number', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.ManyToManyField(blank=True, db_table='plain_image', related_name='plains', to='images.Images')),
            ],
            options={
                'verbose_name': 'Plain',
                'verbose_name_plural': 'Plains',
                'db_table': 'plain',
            },
        ),
    ]
