# Generated by Django 3.2.19 on 2023-05-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20230515_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, error_messages={'unique': 'This name is already taken.'}, max_length=30, null=True, unique=True),
        ),
    ]
