# Generated by Django 3.2.19 on 2023-05-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20230524_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='desc',
            new_name='descriptions',
        ),
    ]
